output_dir = "./repo-serialized"

ignore_patterns = [
    "^repo-serialized/",
]

[[priority_rules]]
score = 100
pattern = "^src/"

[[priority_rules]]
score = 70
pattern = "^src/lib/"

[[priority_rules]]
score = 70
pattern = "^test/"

[[priority_rules]]
score = 30
pattern = "^scripts/"

[[priority_rules]]
score = 10
pattern = "^src/defaults\\.rs$"
