output_dir = "./repo-serialized"

[ignore_patterns]
patterns = [
    "^repo-serialized/",
    "^tests/.*",
    "^.*\\.txt$",
    "^benchmarks/",
    "^src/defaults\\.rs$",
    "^\\.github/.*$",
    "README.md",
    "CHANGELOG.md",
    "^LICENSE$",
    "^README$",
]

[[priority_rules]]
score = 100
patterns = ["^src/"]

[[priority_rules]]
score = 70
patterns = ["^src/lib/", "^test/"]

[[priority_rules]]
score = 30
patterns = ["^scripts/"]

[[priority_rules]]
score = 10
patterns = ["^src/defaults\\.rs$"]

output_dir = "./repo-serialized" 