name: AI Fix Loop

on:
  push:
    branches:
      - ai-loop # Remove me after testing
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to run the workflow on"
        required: true
        default: "tokenizer" # Default branch to main after testing
        type: string
      attempts:
        description: Maximum number of attempts
        default: "40"

permissions:
  contents: write
  pull-requests: write

jobs:
  loop:
    name: AI Fix Loop
    runs-on: ubuntu-latest
    timeout-minutes: 360 # Maximum allowed by GitHub
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"
      - name: Install askds
        run: npm install -g askds

      - name: Install Yek
        run: curl -fsSL https://bodo.run/yek.sh | bash

      - name: Build
        run: cargo build

      - name: Run AI Fix
        timeout-minutes: 360
        env:
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
          FIREWORKS_AI_API_KEY: ${{ secrets.FIREWORKS_AI_API_KEY }}
          RUST_TEST_TIMEOUT: 300
          MAX_ATTEMPTS: ${{ github.event.inputs.attempts || '40' }}
        run: ./scripts/ai-loop.sh

      - name: Upload attempts log
        uses: actions/upload-artifact@v3
        with:
          name: attempts-log
          path: attempts.txt

      - name: Push changes
        if: success()
        run: |
          git checkout -b ${{ github.event.inputs.branch }}-ai-fix-${{ env.SHORT_DATE }}
          git push origin ${{ github.event.inputs.branch }}-ai-fix-${{ env.SHORT_DATE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create PR
        if: success()
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "AI Fix"
          title: "AI Fix for ${{ github.event.inputs.branch }} (Attempts: ${{ env.ATTEMPTS }})"
          body: |
            ## AI Fix Results
            - Total attempts made: ${{ env.ATTEMPTS }}
            - Source branch: ${{ github.event.inputs.branch }}
            - Fix branch: ${{ github.event.inputs.branch }}-ai-fix-${{ env.SHORT_DATE }}

            **Important Notes:**
            - Review all changes carefully
            - Verify test results
            - Check the [workflow artifacts](#) for detailed attempt logs
          branch: ${{ github.event.inputs.branch }}-ai-fix-${{ env.SHORT_DATE }}
          base: ${{ github.event.inputs.branch }}
